# -*- coding: utf-8 -*-
"""Contador de MACROS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luaB5SMsbecS_y1QUQqsXuTGQ5Pl3g0p
"""

# BASICOS SOBRE LISTAS I DICCIONARIOS EN PYTON

lista = ["Ruslan", 1.71, "Russia", True]
print(lista[2])

lista1 = ("Espanya", 1.2, "Kazahistan", False)

print(lista1[1])

diccionario = {
    "nombre": "PEPITO",
    "pais": "Russia",
    "altura": 1.7,
    "estado": True
}

print(diccionario["nombre"])

usuario_datos = {
    "Usuario": "Ruslan"
    "Contrasenya": "Hoquei"
}

inicio_sesion = {
    "Usuario": input("Ingrese su usuario porfabor")
    "Contrasenya": input("Ingrese su contrasenya")
}

if inicio_sesion["Usuario"] == usuario_datos["Usuario"] and inicio_sesion["Contrasenya"] == usuario_datos["Contrasenya"]
print("CARGANDO. INICIANDO SESION")

elif inicio_sesion["Usuario"] != usuario_datos["Usuario"]
print("Usuario inexistente")

elif inicio_sesion["Contrasenya"] != usuario_datos["Contrasenya"]
print("Contrasenya incorrecta, por fabor vuelva a intentarlo")

#OPERADORES ARITMETICOS

suma = 2 + 2
print(suma)

divi = 12 / 5
print(divi)

#OPERADORES DE COMPARACION (MUY IMPORTANTE )

# == es iugal que
# != es distinto que
# < es menor que
# <= es menor o igual que
# > es mayor que
# >= es mayor o igual que

igual_que = 5 == 6
print(igual_que)

distinto_que = 3 != 2 +5
print(distinto_que)

print("-"*50)

a = 60
b = 90
c = 25
d = 13.75

operacion = a / b - d

usuario_datos = {
    "Usuario": "Ruslan",
    "Contrasenya": "Hoquei"
}

inicio_sesion = {
    "Usuario": input("Ingrese su usuario porfabor   "),
    "Contrasenya": input("Ingrese su contrasenya   ")
}

if inicio_sesion["Usuario"] == usuario_datos["Usuario"] and inicio_sesion["Contrasenya"] == usuario_datos["Contrasenya"]:
    print("CARGANDO. INICIANDO SESION")

elif inicio_sesion["Usuario"] != usuario_datos["Usuario"]:
    print("Usuario inexistente")

elif inicio_sesion["Contrasenya"] != usuario_datos["Contrasenya"]:
    print("Contrasenya incorrecta, por fabor vuelva a intentarlo")

#CONVERSOR DE UNIDADES ACTIVIDAD

kms_to_mls = 0.62
eur_usd = 1.18


unidades_a_convertir = input("""Que unidades desea convertir? INTRODUCE EL NUMERO DE LA LISTA\n 1- kilometros a millas\n 2- euros a dolares\n 3- celsius a farenheit    """)

#KILOMETROS A MILLAS

if unidades_a_convertir == "1":
  kms = float(input("Introduce kilometros"))
  print(f"{kms} kilometros son {kms * kms_to_mls} millas")

elif unidades_a_convertir == "2":
  eur = float(input("Introduce euros"))
  print(f"{eur} euros son {eur * eur_usd} dolares")

elif unidades_a_convertir == "3":
  cels = float(input("Introduce Celsius"))
  farenheit = (cels * 9/5) + 32
  print(f"{cels} grados celsius son {farenheit} grados Farenheit")

# ==========================================
# CONVERSOR UNIVERSAL
# ==========================================

# Factores base (siempre convertimos a una unidad base primero)
conversiones = {
    "distancia": {
        "km": 1,
        "m": 0.001,
        "millas": 1.60934
    },
    "dinero": {
        "eur": 1,
        "usd": 1.18,
        "gbp": 0.85
    },
    "temperatura": "especial"
}

# ==========================================
# FUNCION TEMPERATURA (porque no es lineal)
# ==========================================

def convertir_temperatura(valor, origen, destino):

    # Pasamos todo primero a Celsius
    if origen == "c":
        celsius = valor
    elif origen == "f":
        celsius = (valor - 32) * 5/9
    elif origen == "k":
        celsius = valor - 273.15
    else:
        return "Unidad no válida"

    # De Celsius a destino
    if destino == "c":
        return celsius
    elif destino == "f":
        return (celsius * 9/5) + 32
    elif destino == "k":
        return celsius + 273.15
    else:
        return "Unidad no válida"

# ==========================================
# PROGRAMA PRINCIPAL
# ==========================================

print("Categorías disponibles:")
for categoria in conversiones:
    print("-", categoria)

categoria = input("Elige categoría: ").lower()

if categoria not in conversiones:
    print("Categoría no válida")
else:

    valor = float(input("Introduce valor: "))
    origen = input("Unidad origen: ").lower()
    destino = input("Unidad destino: ").lower()

    # Temperatura
    if categoria == "temperatura":
        resultado = convertir_temperatura(valor, origen, destino)
        print(f"\nResultado: {round(resultado,2)} {destino}")

    # Distancia o dinero
    else:
        unidades = conversiones[categoria]

        if origen not in unidades or destino not in unidades:
            print("Unidad no válida")
        else:
            # Convertimos a unidad base
            valor_base = valor * unidades[origen]
            # Convertimos de base a destino
            resultado = valor_base / unidades[destino]

            print(f"\nResultado: {round(resultado,2)} {destino}")

#CRM PEDIDOS

print("Menu del programa de gestion de pedidos")
int(input("Seleccione la accion que queira realiza"))

# ==========================================
# SIMULADOR DE INVERSION PROFESIONAL
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("=== SIMULADOR DE INVERSION ===\n")

capital_inicial = float(input("Capital inicial (€): "))
rentabilidad_anual = float(input("Rentabilidad anual (%): "))
años = int(input("Duración (años): "))
aporte_mensual = float(input("Aporte mensual (€): "))

# Convertimos rentabilidad anual a mensual
rentabilidad_mensual = (rentabilidad_anual / 100) / 12
meses = años * 12

capital = capital_inicial
historial = []

for mes in range(meses):
    capital = capital * (1 + rentabilidad_mensual) + aporte_mensual
    historial.append(capital)

# DataFrame
df = pd.DataFrame({
    "Mes": np.arange(1, meses + 1),
    "Capital": historial
})

# ==========================
# METRICAS
# ==========================

capital_final = historial[-1]
total_aportado = capital_inicial + (aporte_mensual * meses)
beneficio = capital_final - total_aportado
multiplicador = capital_final / capital_inicial

print("\n===== RESULTADOS =====")
print(f"Capital final: {capital_final:,.2f} €")
print(f"Total aportado: {total_aportado:,.2f} €")
print(f"Beneficio neto: {beneficio:,.2f} €")
print(f"Multiplicador: x{multiplicador:.2f}")

# ==========================
# GRAFICO
# ==========================

plt.figure()
plt.plot(df["Mes"], df["Capital"])
plt.xlabel("Mes")
plt.ylabel("Capital (€)")
plt.title("Evolución del capital")
plt.show()

# ==========================
# ANALISIS AUTOMATICO
# ==========================

print("\n===== ANALISIS =====")

if multiplicador >= 3:
    print("🔥 Estrategia extremadamente rentable")
elif multiplicador >= 2:
    print("🚀 Muy buena rentabilidad")
elif multiplicador > 1:
    print("📈 Rentabilidad positiva")
else:
    print("⚠️ No rentable")

#=== MENU ===

users_registred = ["Juanramon01", "taooo11", "RogerBalletbo", "MireiaVilarMartinez"]


crear_usuario = input("Porfabor, introduzca su usuario:  ")
crear_contrasenya = input("Porfavor, introduzca una contrasenya:  ")

caracteres_especiales = ["@", "#", "!", "%", "$"]

# Check if user already exists
if crear_usuario in users_registred:
    print(f"El usuario '{crear_usuario}' ya existe. Por favor, elige otro.")
else:
    # Validate password criteria
    is_valid_password = True

    if len(crear_contrasenya) < 10:
        print("La contrasenya debe contener un mínimo de 10 caracteres.")
        is_valid_password = False

    # Using 'elif' to only check the next condition if the previous one passed
    # or using separate 'if's if all messages should be shown
    # For this fix, I'll use separate 'if's to show all relevant messages if multiple conditions fail.
    if not any(le.isupper() for le in crear_contrasenya):
        print("La contrasenya debe contener al menos una mayúscula.")
        is_valid_password = False

    if not any(le in caracteres_especiales for le in crear_contrasenya):
        print("La contrasenya debe contener al menos un caracter especial (@, #, !, %, $).")
        is_valid_password = False

    if not any(le.isdigit() for le in crear_contrasenya):
        print("La contrasenya debe contener al menos un número.")
        is_valid_password = False

    if is_valid_password:
        print("REGISTRO EXISTOSO.")
        users_registred.append(crear_usuario)

print(users_registred)

import json

# --- Inicialización ---
macros_totales = {
    "Calorias": 0.0,
    "Proteinas": 0.0,
    "Grasas": 0.0,
    "Carbohidratos": 0.0
}

dias = []  # Lista para guardar todos los días
dia_actual = 1

# Intentamos cargar datos guardados si existen
try:
    with open("macros_semana.json", "r") as f:
        dias = json.load(f)
        if dias:
            dia_actual = len(dias) + 1
except FileNotFoundError:
    pass

# --- Objetivos diarios (ejemplo) ---
objetivo_calorias = 3000
objetivo_proteinas = 150

# --- Menú principal ---
while True:
    print(f"\n--- DIA {dia_actual} ---")
    print("1. Añadir comida")
    print("2. Finalizar día")
    print("3. Mostrar resumen diario")
    print("4. Mostrar resumen semanal")
    print("5. Reiniciar semana")
    print("6. Salir")

    opcion = input("Elige una opción: ")

    # --- 1. Añadir comida ---
    if opcion == "1":
        comida = input("Nombre de la comida: ")
        macros_tomadas = {
            "Calorias": float(input("Calorias: ")),
            "Proteinas": float(input("Proteinas: ")),
            "Grasas": float(input("Grasas: ")),
            "Carbohidratos": float(input("Carbohidratos: "))
        }

        for clave in macros_totales:
            macros_totales[clave] += macros_tomadas[clave]

        print(f"\nComida añadida: {comida}")
        for clave, valor in macros_totales.items():
            print(f"{clave}: {valor}")

    # --- 2. Finalizar día ---
    elif opcion == "2":
        print(f"\nResumen del día {dia_actual}:")
        for clave, valor in macros_totales.items():
            print(f"{clave}: {valor}")

        # Guardar día en lista
        dias.append(macros_totales.copy())

        # Guardar en archivo
        with open("macros_semana.json", "w") as f:
            json.dump(dias, f)

        # Resetear día
        macros_totales = dict.fromkeys(macros_totales, 0.0)
        dia_actual += 1

    # --- 3. Mostrar resumen diario ---
    elif opcion == "3":
        print(f"\nResumen del día {dia_actual}:")
        for clave, valor in macros_totales.items():
            print(f"{clave}: {valor}")

    # --- 4. Mostrar resumen semanal ---
    elif opcion == "4":
        print("\nResumen semanal acumulado:")
        if not dias:
            print("No hay días registrados.")
        else:
            resumen_semanal = dict.fromkeys(macros_totales, 0.0)
            for dia in dias:
                for clave in dia:
                    resumen_semanal[clave] += dia[clave]
            for clave, valor in resumen_semanal.items():
                print(f"{clave}: {valor}")

    # --- 5. Reiniciar semana ---
    elif opcion == "5":
        dias = []
        dia_actual = 1
        macros_totales = dict.fromkeys(macros_totales, 0.0)
        with open("macros_semana.json", "w") as f:
            json.dump(dias, f)
        print("Semana reiniciada.")

    # --- 6. Salir ---
    elif opcion == "6":
        print("¡Hasta luego! Datos guardados en macros_semana.json")
        break

    else:
        print("Opción no válida, prueba de nuevo.")


with open("macros_app.py", "w") as f:
    f.write(codigo)

for clave in macros_totales:
  print(clave)

for valor in macros+totales.value():
  print(valor)

for valor, clave in macros_totales.items():
  print(f"{clave}: {valor}")

for clave in macros_totales:
  macros_totales += macros_tomadas
  print(clave[macros totales])